### PR TITLE
adding a deploy script

### PR DESCRIPTION
**Pull request by choldgraf**

### CODE REVIEW

**Comment by choldgraf** [comment]
This adds a github action auto-deploy. It will

- Install the dependencies
- Build the book
- Push the book's HTML to the `gh-pages` branch of https://github.com/inferentialthinking/inferentialthinking.github.io (where the book is actually hosted)

It uses an RSA key that I've added to this repository (`secrets.DEPLOY_DOCS`) and this key has write access to `inferentialthinking.github.io`.

**Comment by choldgraf** [comment]
@davidwagner this should do the auto-deployments once it's merged in. It assumes that the latest set of book content is in `master`.

Once we're ready for the new book to go live, let me know and we can merge this in to get it auto-deploying. It may take a little bit of debugging to make sure it works properly but shouldn't be too complex.

**Comment by choldgraf** [comment]
@davidwagner where are we with the switch to the new book setup? Let me know if / when I can merge this in (or let me know if you're planning to wait until after the semester or something)

**Comment by papajohn** [comment]
This looks like progress toward using the new version of JupyterBook, so I'm going to merge it and then keep working on the `data8:book_update` branch.

**Pull request merged**
