### PR TITLE
Moving the textbook build to jupyter-book

### PR DESCRIPTION
**Pull request by choldgraf**
Since the original creation of the Jekyll-based build system, I've been working with @SamLau95 to improve this process ([now called "jupyter books"](https://github.com/choldgraf/jupyter-book)). This is also the build system that DS100 uses, abstracted out so that it's class-agnostic.

The main advantages are:

1. The site is much simpler. There are fewer unused CSS styles, templates, includes, etc. This is largely because the old build was based on a Jekyll theme which added a lot of extra cruft.
2. There's more well-crafted JS/CSS in there. I suspect largely because @SamLau95 is a better coder than me :-)
3. There are extra features that weren't there before (e.g. turbolinks fast-loads the pages so they should update much faster, and without the sidebar reloading)
4. The site makes better use of the available space and the CSS is more well-tuned.

The main differences are:

1. The TOC is now specified directly in `_data/toc.yml` instead of being auto-generated by `generate_book.py`. This removes an extra step of auto-complexity and gives us more control over exactly what goes in the sidebar.

That's mostly it (there are some stylistic differences etc but those aren't huge).

This PR will convert the data-8 textbook to use this new system (which will make it easier to bring in future updates as jupyter-book is improved). Before we do this, we should:

* Make sure we're OK with the new build/site system
* Make sure all the links still work properly etc
* Merge this PR over the weekend or sometime when students won't be too surprised.

**[You can find a demo of the new textbook here](https://predictablynoisy.com/textbook/chapters/intro)**. Take a look and let me know if all looks OK.

cc @davidwagner @a-adhikari @papajohn who are probably particularly interested in this.

### CODE REVIEW

**Comment by papajohn** [comment]
Looks great to me! I didn't notice any issues during a brief scan.

**Comment by choldgraf** [comment]
Any others have thoughts on the textbook? If nobody objects, I may try making this switch this weekend...

**Comment by SamLau95** [comment]
Just wanted to mention it in case: we should make sure all existing links to textbook pages will work with the new build system.

**Comment by choldgraf** [comment]
@SamLau95 yep definitely. Do you know of a good way to check a live site for broken links? I believe that all `lower-case` URLs should now redirect to their upper-case versions (which is the current behavior on inferentialthinking.com)

**Comment by choldgraf** [comment]
TIL @SamLau95 is a wizard who can just pull lists of links out of thin air!

yeah I think that's a good idea.

However, I'm a bit hesitant to do this until at least one of the people teaching the class gives there blessing. Out of respect to @davidwagner I'll hold off on making a switch until we hear from him :-)

**Comment by choldgraf** [comment]
@davidwagner said that any time as good as another, so I'm gonna merge this now in the hope that Friday night there are fewer students out there checking the data 8 website. Folks should try all the links they can to make sure that they're still working as expected

**Pull request merged**
